### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by olidroide**
Upgrade SDK android to 24.4.1 and SDK components to 23.0.2

### CODE REVIEW

**Comment by Sloy** [comment]
Hi @olidroide! Thanks a lot for the contribution! I appreciate it.

Just one question: are those new components needed? I'm talking about `extra-android-support,extra-google-google_play_services,extra-google-analytics_sdk_v2`. What are they needed for? I didn't find any problems using the support library and play services with the current environment.

**Comment by olidroide** [comment]
You're welcome @Sloy Thanks for support me ;)

I have problem with the build. This failed with this message:

`Could not find com.android.support:appcompat-v7:23.1.1.` you can find the whole result here: https://gitlab.com/olidroide/Android-GitLab-CI-Example/builds/440914

I think need the `extra-android-support` for working properly. The project than I wanna build have these dependencies:

```
dependencies {
  compile fileTree(dir: 'libs', include: ['*.jar'])
  testCompile 'junit:junit:4.12'
  compile 'com.android.support:appcompat-v7:23.1.1'
}
```

Is very simple project

**Comment by Sloy** [comment]
I see. I don't think it's related to the missing components, but to the version installed in the docker image. Let me test a couple of things and I'll get back to you ;)

**Comment by olidroide** [comment]
thanks! :)

**Comment by Sloy** [comment]
@olidroide Hey! Sorry for the delay, couldn't find the right time. I see in your Gitlab CI that the build is passing already for the same commit that failed previously. All I did is trigger a rebuild for the 23.latest tag on Docker Hub.

The problem was, I believe, that the extra repositories are not versioned. When the last build was made it didn't have the _ version available. But when a new build is done, they are. Too bad.

So please, if you don't mind revert the last commit or remove the extra components. The two first commits are super handy, I will merge them and tag a new version of the docker image.

PS: I recommend you to use specific versions of the docker image instead of *.latest, so your builds are fully deterministic. When you need a newer version you change the tag in the gitlab config file. This way you make sure that environment changes don't break builds because of dependencies or what not (eg: build-tools update)

:)

**Comment by olidroide** [comment]
Thanks @Sloy I will revert the changes without extra components.

What do you think about create a `ENV ANDROID_TARGET android-23` to use one `ANDROID_TARGET` is more clean for understand it?

Thanks for the advise about the use the lastest build, I will change it too in GitLab project.

**Comment by Sloy** [comment]
Yes @olidroide, I think that change is nice. Sorry for not mentioning it.

**Comment by olidroide** [comment]
Hi @Sloy I already update the Pull request ;)

**Comment by Sloy** [comment]
Merged! You can use the updated image `sloydev/android-env:23.2` (well, when [builds](https://hub.docker.com/r/sloydev/android-env/builds/) are finished)

**Comment by olidroide** [comment]
Thanks! :)

**Pull request merged**
