### PR TITLE
Upgrad Gradle version

### PR DESCRIPTION
**Pull request by olidroide**
I upgrade the last version of Gradle.

### CODE REVIEW

**Comment by Sloy** [comment]
Hey thanks! I tried building this and it failed because of the md5 checksum.

Could you make sure that you got the hash of the right file? You get it executing `md5 {filename}` on OSX or `md5sum {filename}` on linux.

If you get the same output hash I will investigate further.

**Comment by olidroide** [comment]
Ooopps! I update the md5sum, I don't know what md5 file I put there... sorry!

**Comment by Sloy** [comment]
Seems to work now. I'm merging and creating the updated tag in Docker Hub. Thanks a lot @olidroide! :heart:

**Comment by Sloy** [comment]
Done! Your change is now present in _23.3_, _latest_ and _23.latest_ docker tags.

**Pull request merged**
